site_name: Alpha X Documentation

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: images/favicon.png
  logo: assets/logo.png
  palette:
    primary: 'white'
    accent: 'gray'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - index.md
  - supported.md
  - Games:
    - Bloxburg:
      - Introduction: Games/Bloxburg/intro.md
      - Ban Risk: Games/Bloxburg/banrisk.md
      - Auto Build: Games/Bloxburg/autobuild.md
      - Auto Farm: Games/Bloxburg/autofarm.md