site_name: Alpha X Documentation

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: images/favicon.png
  logo: assets/logo.png
  palette:
    primary: 'white'
    accent: 'gray'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/styles.css

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

plugins:
  - search

nav:
  - index.md
  - discord.md
  - supported.md
  - Games:
    - Adopt Me:
      - Introduction: games/AdoptMe/intro.md
    - Bad Business:
      - Introduction: games/BadBusiness/intro.md
    - Bloxburg:
      - Introduction: games/Bloxburg/intro.md
      - Ban Risk: games/Bloxburg/banrisk.md
      - Auto Build: games/Bloxburg/autobuild.md
      - Auto Farm: games/Bloxburg/autofarm.md
    - Lumber Tycoon 2:
      - Introduction: games/LumberTycoon2/intro.md
    - Phantom Forces:
      - Introduction: games/PhantomForces/intro.md
    - Ragdoll Engine:
      - Introduciton: games/RagdollEngine/intro.md
    - RoBeats:
      - Introduction: games/RoBeats/intro.md
    - Sound Space:
      - Introduction: games/SoundSpace/intro.md
    - Strucid:
      - Introduction: games/Strucid/intro.md
    - Tower of Hell:
      - Introduction: games/TowerOfHell/intro.md
  - credits.md